### ISSUE TITLE
How to build it

### ISSUE THREAD

**Issue by und3fined** [dvc94ch/noxc#1]
Hi there

First, I not a swift(er).
I use command `swift build --product noxc --configuration release --triple arm64-apple-macosx` for try build script but got a error

```
'noxc': error: public headers ("include") directory path for 'corecrypto' is invalid or not contained in the target
```

Can U help me build it or re-config corecrypto for it work?

**Comment by dvc94ch** [comment]
so I never actually got it to work. I didn't know about https://github.com/n3d1117/cook when I did this, and I got an apple developer subscription now as I got fed up with messing about with this. Good luck!
